### ISSUE TITLE
Create utility functions signatures

### ISSUE THREAD

**Issue by nicolocarpignoli** [AR-js-org/studio-backend#1]
Create a set of initial and mandatory utility methods with a signature, specifying at least input parameters

**Comment by sigalor** [comment]
I think it doesn't make much sense to have this as a separate task. After all, utility functions are created once they're actually needed; of course we don't know the implementation details of the code we'll be writing in advance, so we don't know which utility functions we need yet.

**Comment by nicolocarpignoli** [comment]
I totally agree, I was thinking that could help you but I'm seeing that you are learning very fast the AR ecosystem :) closing this!
