### ISSUE TITLE
Create a 'Text' provider

### ISSUE THREAD

**Issue by le0m** [AR-js-org/studio-backend#10]
This provider should output the application bundle as a UTF-8 string for the frontend.

**Comment by pedrovrima** [comment]
'Hey @le0m , just to clarify: is "application bundle" the output from handlebar.js?

**Comment by le0m** [comment]
Hi @pedrovrima. Sorry if I wasn't clear, with "application bundle" I mean the output of this module. I used that phrasing to be consistent with the other providers (GitHub and Zip).

The general design is that handlebar.js generates the file contents, then we use different providers to package those in different "bundles".

This implementation should simply take file contents as input and return them as output, to be shown to the user by the frontend application. This is for the usecase in which the user wants the application in text format to be copy-pasted.

**Comment by pedrovrima** [comment]
Hey @le0m, thanks for the clarification! 

I just looked at the zipProvider and github and the idea is to create something similar to that - extending BaseProvider with a addFile and a serveFile function - right? 
The difference would be in the serveFiles - this would serve a txt for the frontend, right?

Sorry for asking so many question. I am very begginer but want to help as much as I can!

**Comment by le0m** [comment]
No problem, this is not well documented and I made the issues also to discuss the details ^^

You got It right, with serveFiles the text provider should serve txt content of the files to the frontend.

**Comment by pedrovrima** [comment]
Great! I think I can help with that. Just one last question: which are the
files to be inputed in this provider? The code is quite obvious, but are we
outputing the marker and the 3d model as txt as well? I am sorry, don't
know if that even makes sense hehe

Em qua., 19 de fev. de 2020 às 17:58, le0m <notifications@github.com>
escreveu:

**Comment by le0m** [comment]
You can treat marker files like any other file, because input images are supposed to be base64-encoded strings. Each file added has an `encoding` parameter, so for this provider we can return It with `serveFiles()` to let the frontend handle It.

I didn't think about the 3d model assets yet, was waiting for the frontend prototype to have a better understanding of what we need.

Questions and suggestions are welcome, they help to think about how to wrap all this up ^^

**Comment by le0m** [comment]
Copy & paste may result cumbersome with assets, so this has been put on hold.

As a possible solution we could add a text on the frontend that tells the user to put his assets in `some/path`.

**Comment by pedrovrima** [comment]
Hey @le0m, sorry for the long time without news. I will be taking care of this next week, if no one has done so. I can also take my time to solve any other *simple* issues

**Comment by le0m** [comment]
It's ok, this is not top priotity ^^
