### ISSUE TITLE
Create a 'Package' module

### ISSUE THREAD

**Issue by le0m** [AR-js-org/studio-backend#13]
This is a class that exposes (static?) methods to the frontend to generate the application package and "give" It to the user.

The interface could be somethings like this:

```js
const package = new Package(type, config);
package.serveFiles('zip/github'); // uploads to GitHub or returns a Zip file
```
Where `type` is one of `location/barcode/pattern/ntf` and each one can have It's own`config`:
- barcode
```js
{
  matrixType: 'see exported consts',
  value: 123
}
```
- pattern
```js
{
  image: 'data URI string',
  ratio: 0.5,
  size: 128,
  color: '#000000'
}
```
- location
```js
{
  lat: 99.7766
  lon: 77.8844
}
```

Internally, the module should:
- use `MarkerModule` to generate marker image (for barcode and pattern) and patt file (only for patter)
- use the handlebar.js wrapper to generate the HTML
- input the file in a provider and return the results

I think both GitHub and Zip providers will need adjustments for handling 3d models, but binary files should be already sort-of implemented.

**Comment by nicolocarpignoli** [comment]
As for now, for the MVP of this project, we are not supporting barcode.
What we are supporting now is:

* markers (pattern)
* location based.

I suggest to create two different methods, one is serveGithub, the other serveZip.

The function to create the package should be the one, apart from the later phase of serving.

**Comment by le0m** [comment]
## Marker pattern

The final package should contain these files:
- `index.html` file from templates (generated with `PatternPackage`)
- AR asset file (uploaded by user)
- full marker image with border (generated with `MarkerModule`)
- `.patt` marker file (generated with `MarkerModule`)

### Generate HTML

`PatternPackage.generateHtml()` requires these parameters:
- AR asset type (to pick the right template, chosen by user), we currently support:
  - 3d model
  - image
  - audio
  - video
- relative path to the `.patt` file, used in the template (we could hardcode this, eg. `/assets/marker.patt`)
- relative path to the AR asset file, used in the template (we could hardcode this based on the asset type, eg. `/assets/ar-asset.gltf`)
- could require more in the future, eg. scale and rotation

### Generate marker image with border

`MarkerModule.getFullMarkerImage()` requires these parameters:
- original image as dataURI string (uploaded by user and converted by frontend)
- ratio of border size over image size as float number (chosen by user)
- full marker size in pixels as integer (chosen by user)
- color of border as hex color (chosen by user)

### Generate marker patt file

`MarkerModule.getMarkerPattern()` requires one parameter:
- original image as dataURI string (uploaded by user and converted by frontend)

### Example interface

An example of usage could be this:
```js
// create package for marker pattern with 3d model
const package = new Package({
  arType: 'pattern',
  assetType: '3d',
  assetFile: modelFile, // File object from form
  markerImage: MarkerModule.getFullMarkerImage(imageData, 0.5, 512, '#000'),
  markerPatt: MarkerModule.getMarkerPattern(imageData)
});

// generate zip file as blob 
const packageFile = package.serveZip({
  type: 'blob',
  compress: 7
});
```

**Comment by nicolocarpignoli** [comment]
that's great
