### ISSUE TITLE
Fix README Modules Example

### ISSUE THREAD

**Issue by mingir2** [AR-js-org/studio-backend#14]
1. MarkerModule.getBarcodeMarkSVGDataURI returns out of range error when the barcode value is 8 or more. Any barcode value less than 8 does not return an error. The README example uses 8 as an example, so I'm guessing it's a bug, perhaps off by 1.
```js
const barcodeMarkerSVG = MarkerModule.getBarcodeMarkerSVGDataURI(MATRIX_3X3_HAMMING_63, 8);
```
```
Error: barcode value out of range: 8
```

2. PattFileDownload.click() triggers the download correctly, but the downloaded file is [object Promise]. I'm not 100% sure about whether there is a more correct way to do this, so that the download returns an actual patt instead of a promise.
```js
pattFileDownload.click(); // trigger download
```
```
[object Promise]
```

**Comment by le0m** [comment]
1. I put 8 without thinking ^^" the maximum value you can use depends on the matrix type (see [here](https://github.com/AR-js-org/studio-backend/blob/master/src/modules/marker/tools/barcode-marker-generator.js#L10), different matrix types have different `maxNumMarkers`).
I added a table to the readme and fixed the example, but maybe we should reference some external guide about the matrix types.

2. I forgot the `await` when calling `MarkerModule` methods, I fixed this example too

**Comment by mingir2** [comment]
Thank you! @le0m
