### ISSUE TITLE
Create a 'dist' folder in versioning, that can be referenced from outer libs

### ISSUE THREAD

**Issue by nicolocarpignoli** [AR-js-org/studio-backend#15]
It should be possible to have the minified (and not mifinified) version on the lib available on this repository, that can then be retrieved using services like https://raw.githack.com/, to be imported in other libraries (like `studio`, the frontend project).

What do you think @le0m ?

This will avoid the manual import of the minified library on `studio` project.

**Comment by le0m** [comment]
Sure, I'll look into It this week :+1:
