### ISSUE TITLE
Import pattern marker generator as a method

### ISSUE THREAD

**Issue by nicolocarpignoli** [AR-js-org/studio-backend#2]
Implement the pattern marker generator behaviour in a method.

When given parameters regarding input images (base64 maybe?) and other like border thickness and color, it outputs .patt file and .png (base 64 again?) of the generated marker.

behaviour is practically the same of: https://jeromeetienne.github.io/AR.js/three.js/examples/marker-training/examples/generator.html

**Comment by sigalor** [comment]
Is there a formal definition of the .patt file format? I only know of [mk_patt](https://github.com/artoolkit/artoolkit5/blob/master/util/mk_patt/mk_patt.c), which is part of ARToolKit. According to [this page](http://www.hitl.washington.edu/artoolkit/documentation/devmulti.htm), it even seems like mk_patt needs to access the webcam to be able to be "trained".

The generator you linked to uses a custom implementation called [`THREEx.ArPatternFile`](https://github.com/jeromeetienne/AR.js/blob/master/three.js/examples/marker-training/threex-arpatternfile.js) instead. Does that JS source originate from somewhere else and is maybe even contained in some existing NPM module or has it been written only specifically for this generator?

**Comment by nicolocarpignoli** [comment]
I don't know about your question. For this task we 'just' need to re-use the code behind the online web pattern marker generator I linked. I don't think there is an NPM module. Jerome (the author) probably wrote this one himself.

**Comment by le0m** [comment]
I submitted a PR for the pattern marker generator, if anyone wants to review It. It's missing tests.

@sigalor my understanding is that the `.patt` file format has no formal definition outside of the artoolkit5 and AR.js implementations. BTW, the `mk_patt` you linked is now returning a 404 (It was working yesterday). It seems like the artoolkit organization removed the repository from GitHub, does anyone knows what happened?

**Comment by nicolocarpignoli** [comment]
if you need artoolkit repo can be found as a fork on a lot of accounts on Github. For docs, there's: https://github.com/nicolocarpignoli/artoolkit-docs

**Comment by nicolocarpignoli** [comment]
done!
