### ISSUE TITLE
Create GitHub account to hosts user's projects

### ISSUE THREAD

**Issue by le0m** [AR-js-org/studio-backend#30]
For the MVP, we decided to use a new GitHub account to generate a token, and hard-code that account/token into the Studio app.
When users create a project from Studio and decide to host it on GitHub, we'll use this account and create a new repository for deploying and hosting the project.

**Comment by nicolocarpignoli** [comment]
I will create a new AR.js Studio org only for this purpose.

**Comment by mingir2** [comment]
We should also look into using single repo with multiple .html and asset files. Someone mentioned this in the last meeting and I think it's worth a consideration.

**Comment by nicolocarpignoli** [comment]
That would be okay for MVP but bad post  MVP because we cannot give to user a URL to use to  modify their project because it will be on one repository own by us.

**Comment by nicolocarpignoli** [comment]
Done: https://github.com/ARjsStudio @le0m will give you credentials on private chat
