### ISSUE TITLE
Sporadic problem when getting github shareable link

### ISSUE THREAD

**Issue by gciandro13** [AR-js-org/studio-backend#45]
A sporadic problem was reported: it happens in a random way when trying to getting github shareable link (error on screenshot). 

![image](https://user-images.githubusercontent.com/20702863/94132352-76668580-fe5f-11ea-89b0-5c5e1fb395d9.png)

**Comment by le0m** [comment]
Did you notice if it happens only with a specific type of asset (ex. gltf model, video file, ...)? Does it happens with both location-based and marker-based?

**Comment by gciandro13** [comment]
From the user:

"It seems to be with location based and marker based projects. It was mostly when I was using gltf files. I have found that some gltf files work, and some do not work. I’m not sure if it is because of the type of gltf file, or the size of the gltf? But I tried to make sure that they were under the size requirement stated on the ar.js"

**Comment by thauska** [comment]
This error appears to me. I uploaded an PNG file.

**Comment by thauska** [comment]
> From the user:
> 
> "It seems to be with location based and marker based projects. It was mostly when I was using gltf files. I have found that some gltf files work, and some do not work. I’m not sure if it is because of the type of gltf file, or the size of the gltf? But I tried to make sure that they were under the size requirement stated on the ar.js"

The person that test it, was using the Ads Block plugin?

**Comment by gciandro13** [comment]
The user reported that the problem is still there, and it is related with some gltf files; sometimes it work, sometimes not.
I think that this is not a general issue; so my opinion is to close it @le0m
 
I think that if he sends to me some problematic files, we can take a look on that; maybe if we understand what is the problem, we can anticipate the error on uploading stage.. (I guess)..
